### ISSUE TITLE
meetup can happen with only one participant.

### ISSUE THREAD

**Issue by clangenb** [encointer/pallets#103]
Probably, this only happens if only one participant is registered for the whole CommunityCeremony.

**Comment by brenzi** [comment]
can be fixed with help of pallets#107

**Comment by NicJak** [comment]
I would propose the following:

within generate_meetup_assignment_params() implement a rule based on assignment_count*
when this rule applies, all inserts of generate_meetup_assignment_params() are either skipped or replaced by defaults. I would prefer the latter.

* these rules are based on AssignmentCount, I suppose, we would just check for the sum to be greater than 1?

**Comment by clangenb** [comment]
We can just skip. The storage map implementation of substrate is optimized such that keys containing the default value do not even exist. This is done to save storage space on the blockchain. Hence, I suggest we just skip the rest of the function when assignment count here is 0:

https://github.com/encointer/pallets/blob/6b186faebdf99059272ba1729a0b4e9d9db08edb/ceremonies/src/lib.rs#L489

The same goes for meetup_count. We don't need to bother entering 0 here, as it will not have any effect anyhow.

However, assignment count should be checked for >= 3.
