### ISSUE TITLE
purge inactive communities

### ISSUE THREAD

**Issue by brenzi** [encointer/pallets#107]
maintain a storage that tracks
* how many successul meetups have been performed per cindex

upon new ceremony phase, purge communities which had 0 successful meetups for the last N ceremony phases. N should be a runtime constant

this storage should only be N+1 deep (not store all history)

**Comment by NicJak** [comment]
wouldn't it be easier to implement a number per community that just counts the 0-meetings? This off course wouldn't allow for fancier logic to purge communities, but is far less memory/computation intensive and probable simpler to implement as well..

on_new_phase:
for cid in cids:
  if no_meetups(cid)
     inactivity_counter[cid] ++
     if inactivity_counter[cid]> MAX_INACTIVITY:
       purge(cid)
  else
     inactivity_counter[cid]=0

**Comment by brenzi** [comment]
Yes, that would work. but it won't happen on new phase. Due to lazy issuance, we only know the number of successful meetups at the end of registering / start of assigning. So I guess that is the best moment to check and purge

**Comment by clangenb** [comment]
Closes by #115
