### ISSUE TITLE
optimize performance of reputation rpc getter

### ISSUE THREAD

**Issue by brenzi** [encointer/pallets#118]
Currently we have a very expensive implementation (#113) for getting all reputation history for one AccountId. 

Elsewhere, we use offchain indexing to allow more performant cached queries:

https://github.com/encointer/pallets/blob/master/communities/rpc/src/lib.rs
cache update triggered by:
https://github.com/encointer/pallets/blob/e3c4d7fc9a2ca66f8589842a9ef432bf4129ef7c/communities/src/lib.rs#L135

For this we should invert the mapping of the storage in the cache: from 
https://github.com/encointer/pallets/blob/e3c4d7fc9a2ca66f8589842a9ef432bf4129ef7c/ceremonies/src/lib.rs#L101
(which is correct for the runtime pallet, because we need purge by cindex to be cheap)
to:
```
AccountId-> Vec<(Community, Reputation)>
```
because the rpc will query by account, not by cindex or community.

The cache should always return a vec of length (ReputationLifetime) with tuples of Community and Reputation. The tuple makes sense if that accountid has participated in more than one community in the recent ceremonies (and we're sure by design that one accountid can't participate in two communities for the same ceremony....however, technically, we should handle that collision somehow) 

Good thing about caching: the cache only gets dirty once per ceremony, so the refresh may be costly if we gain significant query performance benefits

**Comment by NicJak** [comment]
Some alternate signature proposal as arised from discussion:
`AccountId -> Vec<CommunityCeremony>`
Then, the size of Vec does not always have to be of MaxReputationLifetime and no implicit timing information is contained. If we choose the (Community, Reputation) version, I would propose not to use Vec, but an array, as it will be of fixed length.
Also: will clients be interested in the actual distinction of the different Reputation enums or would it suffice to tell, that they were reputable in a community at a point of time. If so, we could remove the proposed Reputation and just return a vector of communities. The change towards communityceremony would then only mean the explicit encoding of the ceremonyindex as to the implicit that has to be computed from the position within the array.

**Comment by brenzi** [comment]
Good point. But then I suggest
```
AccountId -> [Option<Community>; ReputationLifetime]
```
We need to specify the cindex in our rpc reply, but no need to store it with every array element

**Comment by brenzi** [comment]
what a surprise, this hits us already:
```
time ./encointer-client-notee reputation 5EFbay2uvdfCCnQLFYRp9ozaP3X4868enZDRE27HyGKcJ9qD
384, u0qj94fxxJ6, Reputation::VerifiedUnlinked
532, u0qj94fxxJ6, Reputation::VerifiedUnlinked

real	0m17.920s
user	0m0.005s
sys	0m0.010s

```

**Comment by brenzi** [comment]
We could purge unneceasary communities, that would also help

**Comment by brenzi** [comment]
cache gets dirty with every claim_rewards()
rpc may want to refresh cache after each claim_rewards call that issues rewards

**Comment by clangenb** [comment]
I'd say we make the cache per account.

While issuing rewards, we should do something like:

`sp_io::offchain_index::set([CACHE_DIRTY_KEY, account.encode().as_slice()].concat()', &true.encode());`

Here:

https://github.com/encointer/pallets/blob/e389cb4b536134dacb63839029e0098044146331/ceremonies/src/lib.rs#L1345

**Comment by brenzi** [comment]
we purged unnecessary history on Gesell now, reducing rpc response time from 33s to 850ms

comparing to list-locations, which is cached and takes 700ms, I guess we can only win 150ms with caching. However: it's not only about response time, it's also about load on the rpc node. And that will be reduced if we don't need to spawn a wasm interpreter to answer rpc

**Comment by brenzi** [comment]
this is issue should only be closed after integration with the node and a latency test

**Comment by clangenb** [comment]
Integration has happened, we only need to test now.
