### ISSUE TITLE
add more events to ceremonies pallet

### ISSUE THREAD

**Issue by clangenb** [encointer/pallets#130]
The ceremonies has only one event currently: `ParticipantRegistered`. We can for sure enrich the events there, e.g.:

* `EncorsedNewcomer`
* diversify `ParticipantRegistered` into `BootstrapperRegistered`, `ReputableRegistered`, `EndorseeRegistered`, `NewbieRegistered`
* `RewardsClaimed`

And some others.

**Comment by brenzi** [comment]
don't diversify endorsees, bootstrappers aso as this makes it more complex to subscribe to particiant registrations. Instead, we could add an extra attribute to that event stating the type of participant
