### ISSUE TITLE
newbie assignment limit should be unaffected by endorsee count

### ISSUE THREAD

**Issue by brenzi** [encointer/pallets#140]
Endorsees are effectively newbies too, so I think we should remove endorsee count from the term below

https://github.com/encointer/pallets/blob/e1f167fca918d04fb7c1656fcb4f891322de6998/ceremonies/src/lib.rs#L883-L885

**Comment by brenzi** [comment]
not sure. this will effectively make membership more social-graph like and therefore less inclusive. You'd have to know the bootstrappers in order to join early

**Comment by clangenb** [comment]
Hmm, maybe we want an additional metric; enforce at least `n` reputables or bootstrappers per meetup to ensure that at lest `n` people know how the meetup works.

**Comment by brenzi** [comment]
If we say >1/3 needs to have meetup experience we could also cover the case with 3 particiants with one bootstrapper and 2 endorsees. But that would be risky as one bootstrapper could have undue power without observability by experienced participants

So, a requirement for >=2 experienced p should be fine?
But the question in the OP remains: does it make sense to allow more newbies just because we have endorsees? I think not, so this should be changed

**Comment by brenzi** [comment]
I'd say we leave this as-is. upside is faster community growth potential
