### ISSUE TITLE
implement signed meetup time offset to tune or vary the exact daytime relative to high sun

### ISSUE THREAD

**Issue by brenzi** [encointer/pallets#149]
Story:
* Initially, we'd like the meetup in Zurich to happen at 12:50, not at high sun
* Over time, we may want to shift the meetup time to maximize convenience for all active encointer communities

optional extensions for later (just keep this in mind when designing the solution here): 
* allow drifting: slightly change meetup daytime from ceremony to ceremony within a bounded range. This could be more inclusive overall because everyone will get a chance who has strong time constraints (could be achieved ba manually change this offset after each ceremony)
* allow warping: meetup time moves faster or slower than the sun. This would allow tuning the dateline double-attendance risk

side effects: will require changes in
* encointer-wallet-flutter
* encointer-js
* encointer-node (client)
* encointer-parachain

**Comment by pifragile** [comment]
@brenzi this offset should be global right? and should it be a constant or settable by the `CommunityMaster`?

**Comment by clangenb** [comment]
Global, and settable by `CeremonyMaster`

**Comment by brenzi** [comment]
Yes. And defaulting to zero

**Comment by brenzi** [comment]
#165 implemented the offset as unsigned, but it needs to be signed. Otherwise we can only shift meetup time to later hours, not earlier ones
