### ISSUE TITLE
compute delaunay triangulation for locations per currency before submitting

### ISSUE THREAD

**Issue by brenzi** [encointer/pallets#17]
https://en.wikipedia.org/wiki/Delaunay_triangulation

In order to reduce the computation complexity of location distance onchain, we could require the location map as a delaunay triangulation, effectively reducing the number of distance checks form a fully connected graph

this may help mitigate #9 

We could then extend the idea by saving a centroid per community and maintaining a global delaunay triangulation for all communities (enforcing a maximal intra-community distance together with a minimal inter-community distance)

check out 
https://github.com/mourner/delaunator-rs
feature request for no_std: https://github.com/mourner/delaunator-rs/issues/11

**Comment by clangenb** [comment]
From my understanding of the Delaunay triangulation, we would reduce the intra-community distance check complexity from `O(n^2)` to `O(3n)`, where `n` is the amount of meetup locations in the community being registered. This is clearly a significant amount. This computation is based upon the fact that a 2D Delaunay triangulation yields `n` triangles for `n` points.

However, this reduction does not apply for inter-community distance checks, which means we still have a complexity of `O(M*n^2)` there, `M` being the total number of locations of all the other cids. Thus, we do not mitigate the main load of a community registration.

Only applying intra-community triangulation yields a total complexity of `O(M*n^2 + 3n)`.

Hence, I suggest going with your idea of maintaining a global Delaunay triangulation. When registering a new community, we could even supply an updated global triangulation, which only needs to be validated on-chain. But how do we do this? The distance check is different for each community pair, as we expect different communities sizes.

We could use the centroid and the radius circumventing a community. Then the distance check would be: 
`|C_1 - C_2| > R_1 + R_2`, where `C_i` is the centroids coordinate and `R_i` the radius of the circumventing circle of the two communities in check.

In that case, the total complexity of distance checks for a community registration would be: `O(3C + 3n)`, where `C` is the total number of communities.

Note: This does not include the complexity of validating the triangulation itself. From my understanding, however, this is of linear complexity.

@brenzi do you agree with my computations? And what do you think about my idea for inter-community distance checks?

**Comment by brenzi** [comment]
inter-community distance checks are simplified as well, if you do not allow region-overlap. It is enough to just check the circumference of community A to that of community B, so I don't your complexity calculation is correct.

Maintaining a global delaunay triangulation sounds even less complex, actually. And the centroid approach sounds alright. But we may have to limit a communities' `circumference/area` ratio to avoid malicious location sets

**Comment by clangenb** [comment]
> Only applying intra-community triangulation yields a total complexity of `O(M*n^2 + 3n)`.

I actually believe this is wrong. It should be `O(M*n + 3n)`

**Comment by brenzi** [comment]
I think two-layer delaunay is error-prone. Moreover, on a global level, we're not in 2D, but 3D, not sure what this implies on distances. Probably the DT stays the same and we just have to be careful with distance calc.

Couldn't we just have a single delauney with all meetup locations? We'd need a nice merge algorithm to merge the newly registered DT into the global one

**Comment by clangenb** [comment]
> inter-community distance checks are simplified as well, if you do not allow region-overlap. It is enough to just check the circumference of community A to that of community B, so I don't think your complexity calculation is correct.

I don't quite get that. Do you mean if we only use Delaunay triangulation within currencies?

**Comment by brenzi** [comment]
I'm just saying you don't have to check all locations of the new community against all existing locations. It's enough just to check locations at the circumference of each community

**Comment by clangenb** [comment]
Agreed, single layered might be better. From my perspective the merge algorithm could be fairly simple.

1. Supply an updated triangulation.
2. Node checks if the triangulation is valid.
3. Node checks if all previous locations are included
4. Node checks if the new ones are included.

Inclusion check could be performed in a hashmap, where we store all locations.

**Comment by brenzi** [comment]
We can't submit an updated global triangulation, this is way too heavy.

maybe do it in offchain-workers? And then check it with consensus?

**Comment by clangenb** [comment]
Ok, I believe we should do the global implementation later, and do the intra-community first. This makes the first task not too big, and is a suitable first step regardless the implementation of inter-community handling.

**Comment by brenzi** [comment]
sure, we can start with intra-community.

In the end, we should avoid all `O(n)` complexity in any extrinsic because this either makes fees grow over time or it opens an attack vector. We may be able to accept `O(log(n))`, but that's still very restrictive.

We could get inspired by [offchain phragmen](https://wiki.polkadot.network/docs/en/learn-phragmen#rationale-for-reducing-block-computing-time), where parity solved a similar problem.
We could run a deterministic delaunay algorithm in an offchain worker (executed by all validators/collators) and then find consensus on the result. All validators are actually signing an extrinsic with their result AFAIU, so we could wait for a defined delay or threshold of validators to agree

**Comment by brenzi** [comment]
If we start with intra-community, it should be the client who computes the delaunay and the pallet that verifies it. How is the complexity of validation?

TEE: We could require TEE gateways for community registration while still having all pallets onchain. The TEEs could do the work, as complex as it may be, with integrity.

**Comment by clangenb** [comment]
Yes, it should be the client that computes the delaunay. However, validation is still `O(n)`.

**Comment by brenzi** [comment]
no free lunch.

but quite a step from where we are now. But please make sure DT (not only verification) has a chance to build with `no_std`

**Comment by clangenb** [comment]
`no_std`, should be doable if we depend on substrate-fixed, as `f64` is the only std component (except for `fmt`) from std.

`f64` would be available in `no_std`, but it does not implement some transcendentals, e.g. `sqrt`. But as we want runtime determinism, substrate-fixed woud bee the way to go anyhow.

**Comment by brenzi** [comment]
be aware that substrate-fixed's `asin` is [only valid for small angles](https://github.com/encointer/substrate-fixed/blob/b33d186888c60f38adafcfc0ec3a21aab263aef1/src/transcendental.rs#L442) (in case you need it). Or we'd have to pimp these functions

**Comment by brenzi** [comment]
when the pallet receives a DT to register a new community, we will need to verify that the DT is correct, before checking distances! A malicious actor could supply crossover triangles to register locations that would be too close.

I think it is enough to check that no triangle edges are crossing each other. But I'm not sure if this test actually has similar complexity like computing the DT in the first place. @clangenb can you investigate on this?

**Comment by pifragile** [comment]
> I think it is enough to check that no triangle edges are crossing each other. But I'm not sure if this test actually has similar complexity like computing the DT in the first place.

See `Definition 2.4` and `Lemma 2.3` in [this paper](https://people.eecs.berkeley.edu/~jrs/papers/meshbook/chapter2.pdf). There seems to be a linear verification algorithm for the correctness of the Delauney Triangulation.

**Comment by brenzi** [comment]
Just dumping yesterdays' discussion with @pifragile (please extend if I missed something)

Currently, I believe the very best O(1) approach is to only allow one location to be added per extrinsic, starting with one single bootstrapping location when registering and adding each new location into a global delauney tringulation (or some other structure which allows easy append of new locations with minimal checks, should be close to O(1) - like geohash for example)
