### ISSUE TITLE
Benchmarking follow-up tasks for communities and scheduler pallet

### ISSUE THREAD

**Issue by clangenb** [encointer/pallets#174]
Leftover tasks from #154

- [x] communities benchmarks: extract redundant setup code
- [x] communities benchmarks: the benchmarks take very long because we iterate through `2..500_000` locations, this step-size 1. Let's make this shorter by increasing the stepsize to 25 or even 50.
- [x] communities benchmarks: add verify section after benchmark execution
- [x] scheduler pallet: add verify section after benchmark execution
- [x] re-activate the benchmark test suite for the communities if the test-duration has been significantly reduced.

**Comment by brenzi** [comment]
now that we are O(1), it doesn't make sense to test 500_000 locations anymore, does it? And if, the stepsize should be on a log scale

**Comment by pifragile** [comment]
i implemented a almost worstcase scenario for the location validation. the true worstcase needs some more thorough thinking and probably deserves a separate task: https://github.com/encointer/pallets/issues/185
