### ISSUE TITLE
claim_rewards could be allowed right after the meetup happened

### ISSUE THREAD

**Issue by brenzi** [encointer/pallets#192]
It would be beneficial for UX if the reward would be available shortly after attending a ceremony. As each meetup is validated separately, there is no need to wait until all meetups have happened. We could allow `claim_rewards` in ATTESTING phase, but we need to be careful that every participant had the chance to submit their attestations.

Imagine:
Participants A-D have an internet subscription on their phone and send the `attest_claims`extrinsics only seconds after the meetup closes
Participant E does not have internet connection at that time and needs to go to a place with WiFi to send that extrinsic.
E would be dismissed if claim_rewards would be called before E submits attestations. This we should not allow to happen

**Comment by brenzi** [comment]
If
1. The vote on n/o participants is unanimous
2. The vote yields the majority of assigned participants
3. The numver of attestation submissions matches the vote
4. The connectivity graph of attestations is fully connected and reciprocal

Then the meetup can safely be evaluated instantly

**Comment by pifragile** [comment]
Sounds good.
