### ISSUE TITLE
EncointerBalances pallet should be able to create/manage accounts

### ISSUE THREAD

**Issue by clangenb** [encointer/pallets#201]
We have finally implemented community currencies fees. However, we lack one important feature: we can't pay in community currency when the account has not been created on chain, we get the error `account does not exist`.

Usually, it is the `pallet-balances` that manages accounts on chain, while the the `frame_system::pallet` is the account store.

https://github.com/paritytech/substrate/blob/d4ca1fdd6c8ab9c43c4349761b0b63e47be1081b/frame/balances/src/lib.rs#L225

When a balance of an account is manipulated, it will check in the account store if the account already exists. If not it will call the `frame_system`s pallet `OnNewAccount` hook, which will create an account.

https://github.com/paritytech/substrate/blob/d4ca1fdd6c8ab9c43c4349761b0b63e47be1081b/frame/balances/src/lib.rs#L932

A simple approach to facilitate community-currency-only account could be to simply set the `balances-pallet` existential deposit to 0, and also call the `frame_system`s `OnNewAccount` hook, if we detect that an account does not yet exist on-chain. However, we will not have the possibilities the clean up dust accounts then.

**Comment by brenzi** [comment]
In our case, dust would be:
(NativeBalance < ED) AND for all CC (CcBalance < nominal_income / 10^X)
Maybe we even want to protect any potential reputation of the account

However, demurrage is only lazily applied,. Therefore,  dust will not be removed if people just don't use their accounts anymore

**Comment by clangenb** [comment]
I have looked some more into the account system. This will be feasible without re-setting the ED to 0 of the balances-pallet because the accounts are kept alive by reference counting. The balances-pallet does merely decrease the reference counter when an account's balance falls below the existential deposit. So with the simple approach, we will only have dust accounts if they also have community currency (which, however, will be true for most).

This is how the `assets-pallet` handles accounts: https://github.com/paritytech/substrate/blob/c4dd1bef02b7607018969e79bb16d33c6576ed33/frame/assets/src/functions.rs#L66
