### ISSUE TITLE
Purging community ceremony does not invalidate the reputation cache

### ISSUE THREAD

**Issue by clangenb** [encointer/pallets#219]
Currently, the reputation cache is per account, so is its cache invalidation., but when we purge a CommunityCeremony, we remove  the reputations for all accounts for it.

We probably need to introduce another cache dirty bit, which is global.

Currently, we fail to invalidate the cache, when a CommunityCeremony is purged, which can lead to a participant trying to register with an outdated reputation.

**Comment by brenzi** [comment]
this is a critical bug, but not super-urgent, because the ReputationLifetime is 5 and we are at ceremony index 4 now

yes, a global cache dirty may make sense

**Comment by brenzi** [comment]
Is this now clarified?
