### ISSUE TITLE
Purging a community might lead to storage leak when reputation lifetime changes

### ISSUE THREAD

**Issue by pifragile** [encointer/pallets#247]
When purging a community, we purge cindexes `now-reputation_lifetime..=now`.
example:
if RL is 5 and then we change to 2 and purge a community, we have 3 cindexes that did not get deleted.

**Comment by brenzi** [comment]
yes. we were aware of this. that is why we exposed purge_community_ceremony as a privileged extrinsic for manual cleanup. I don't think we need to solve this automatically
