### ISSUE TITLE
bootstrappers should get reputable endorsement tickets once BS tickets exhausted

### ISSUE THREAD

**Issue by brenzi** [encointer/pallets#287]
Currently, bootstrappers get a one-off allowance for endorsements which does not renew. Reputables get new endorsement tickets for every cycle

This does not make sense if we assume BS to be very active endorsers even after the initial growth phase of the first few cycles

The logic should be:
```
if bootstrapper
  if BS tickets left
    endorse
  else if reputabletickets left
    endorse
  else
    error
```

**Comment by clangenb** [comment]
As you can refill reputable tickets, I would actually first try to endorse and as reputable and then fallback to the bootstrapper tickets, as they are gone forever.
