### ISSUE TITLE
Endorsement by a reputable may burns tickets in the wrong ceremony index.

### ISSUE THREAD

**Issue by clangenb** [encointer/pallets#296]
Regardless of from when the account has the reputation, we always burn the newbie tickets in the current_ceremony index. This is wrong in any case because in the current ceremony index, we can't even have reputation (except after early claims in the attesting phase, but this detail is not relevant here).

We get the current ceremony index here: https://github.com/encointer/pallets/blob/3fc6c4fcef549d32e0ed7beb73ac940b43b25af3/ceremonies/src/lib.rs#L325

Then we check if the user here has any reputation, we don't care which one: https://github.com/encointer/pallets/blob/3fc6c4fcef549d32e0ed7beb73ac940b43b25af3/ceremonies/src/lib.rs#L1269

And then we always burn it in the current ceremony index: https://github.com/encointer/pallets/blob/3fc6c4fcef549d32e0ed7beb73ac940b43b25af3/ceremonies/src/lib.rs#L1274

This needs to be fixed before we have the runtime upgrade.

**Comment by pifragile** [comment]
Why is this wrong? The idea was that you have a certain amount of tickets per cycle if you have reputation. And it only matters that you have reputation not when you got it.

**Comment by clangenb** [comment]
Hmm, so the endorsements per reputation don't accumulate? Ok, I can understand this, I just never understood it this way. It actually might make more sense like this.

**Comment by clangenb** [comment]
Ok, I think this is definitely how it should be. I will close the issue.
