### ISSUE TITLE
Upcoming change in the fungible trait might impact us

### ISSUE THREAD

**Issue by clangenb** [encointer/pallets#301]
I haven't checked it, but it has impacts on the balances pallet so it most likely also will have an impact on our encointer-balances pallet: 
https://github.com/paritytech/substrate/pull/12951

**Comment by pifragile** [comment]
@clangenb there is now a [branch](https://github.com/encointer/pallets/tree/fix-fungibles) that points to the master of substrate and fixes the issues.
how to proceed from here?

**Comment by clangenb** [comment]
Nice. 👍 I would say we wait until this is in a Polkadot release, and then we just incorporate your changes in the next that particular update.

**Comment by brenzi** [comment]
closed elsewhere
