### ISSUE TITLE
new pallet `encointer_reputation_commitments`

### ISSUE THREAD

**Issue by brenzi** [encointer/pallets#303]
For the purpose of [personhood oracle](https://github.com/encointer/encointer-node/issues/300)

In order to get reputation linkability, we need an immutable record of commitments to purposes. While each purpose could maintain such registry for themselves, this is not possible for every purpose. Nostr. for example has no way of referring to a common consensus on commitments. Subsocial could, as they run their own parachain, but it would take integration effort which may slow down adoption. So the Encointer mainnet could provide such a simple registry:

```
pub fn commit_reputation(account_id. cid, cindex, purpose_id: u32, commitment: hash)
  if signature ok and not yet committed to *purpose*
    add commitment to registry double map (purpose, (account_id,cid,cindex))=commitment
pub fn register_purpose(description: String[24])
   append to array (descriptor)
   dispatch Event RegisteredCommitmentPurpose(purpose_id, descriptor)
```
where commitment is the hash of the requesting purpose account (i.e. nostr pubkey) and a random salt which should be unique per call and must later be provided to request a badge

the scope of purposes is global
including unit tests

**Comment by pifragile** [comment]
@OverOrion when is this expected to be ready?

**Comment by OverOrion** [comment]
I haven't started working on it yet as it requires some prerequisite work on my side.
Once I start working on it, I'll let you know.

**Comment by pifragile** [comment]
ok, i could take the task over, as it is blocking me atm. i could start this week and open the PR with this and the KSM faucet next week if everything goes well. @brenzi what do you think?

**Comment by pifragile** [comment]
ok! could you explain in a little bit more depth the rationale behind the commitment hash, as well as the salting mechanism you had in mind?

**Comment by brenzi** [comment]
@pifragile as you implement this pallet for the use with #304, you can ignore R2,R3,R4 because linkability can't be avoided onchain anyway. you can leave the hash empty for your case and the faucet pallet should just check if the reputation has already been used for its purpose
