### ISSUE TITLE
[faucet] allow multiple instances with individual community whitelists

### ISSUE THREAD

**Issue by brenzi** [encointer/pallets#312]
starting from #304, allow anyone to instantiate a new faucet and define a whitelist with cid's that are eligit to drip
Still only for native token (KSM).

new requirements:
* unpermissioned faucet creation where a minimum of funds must be supplied upon creation
* when a faucet runs dry, it gets dissolved and remainders go to the treasury
* each faucet has a whitelist for cid's that are eligible. the whitelist can only be supplied upon creation
* root origin can dissolve a faucet and define a beneficiary accountid where all remaining funds are transferred

the creator of a faucet instance has no special rights whatsoever after creation.

**Comment by pifragile** [comment]
extension: faucet creator has to deposit some KSM on faucet creation. those funds will be reserved and will be refunded when the faucet is either dissolved by root or closed by the creator, once it runs dry.
