### ISSUE TITLE
Feature-gate sybil primitives

### ISSUE THREAD

**Issue by clangenb** [encointer/pallets#33]
Reasoning: https://github.com/scs/substrate-api-client/issues/114

**Comment by brenzi** [comment]
I like this approach!

**Comment by clangenb** [comment]
Feature-gating sybil-primitives does help to get rid of xcm deps in the encointer node.

However, I concluded that removing the branch-id from the substrate dependencies will have more disadvantages than advantages:

If we introduce a feature-gate for polkadot deps, namely sybil-gate and personhood-oracle related stuff, we solve the problems when not using them, but we essentially break the build when we want to use them:

Problems without branch-id:
* test_utils depends on polkadot: solvable could just move the affected to to sybil-template crate
* primitives: same as above
* sybil-gate: bigger problem. It must use polkadot deps, hence needs branch-id. But if it pulls in encointer-primitives, which depends on substrate without branch-id, we get duplicate deps in the sybil-gate. Mitigation: we could redefine the primitives in the sybil-gate, as it is only a few.
* personhood-oracle: biggest problem, depends on encointer-pallets. Can't separate these two.

Furthermore, if we use the `encointer-pallets` for the parachains, we must switch to the rococo-v1 branch anyhow. This cannot be circumvented.

@brenzi you said that the problem is that we often switch between `branch = master` and `branch = rococo-v1`, which implies that dependency management is easier without branch-id, but IMO that is not true. We only switch to rococo-v1 for the `encointer-parachain`, which merely affects the `encointer-pallets`. The `encointer-node` and the  `encointer-client` and thus the `substrate-api-client` are not affected by that.

So what speaks for removing the branch-id? I believe, we don't gain anything.
