### ISSUE TITLE
[democracy] proposal that is long enough in confirming can be cancelled if the lazy update is too late

### ISSUE THREAD

**Issue by clangenb** [encointer/pallets#390]
This is obvious in the code, but I am not sure if this is intended because everything was correct in terms of voting.

https://github.com/encointer/pallets/blob/67ffcfb325d4db46a28e647c7cade5affa17ae2d/democracy/src/lib.rs#L422

**Comment by brenzi** [comment]
The alternatives are not trivial. You don't want enactment to happen arbitrarily late because that may conflict with later proposals
Also, we may not want to synchronously enact with cycle phase changes, because that may lead to overweight

**Comment by clangenb** [comment]
Hmm, I agree that the ceremony phase change should not be used for synchronous enactment, and I don't see any trivial alternative either.

However, we have to be aware that any proposal that is confirmed shortly before its lifetime ends has only a small window to be updated.

**Comment by brenzi** [comment]
We could relax this by prolonging lifetime whenever a proposal enters confirming to at least confirmation period+24h

**Comment by brenzi** [comment]
maybe just swap order of update_proposal_state: check for approval before chacking for expiry

**Comment by clangenb** [comment]
Yeah, but this would again conflict with what you said above: "prevent arbitrary late execution that may conflict with another proposal". However, now that I think of it, conflict can't happen as this proposal would have been cancelled with the enactment of the other proposal on the same track.

So maybe allowing arbitrary late enactment is fine after all.

**Comment by brenzi** [comment]
Equally confusing is cancellation by other approved ref of same type. The UI really needs to know why a proposal was canceled. Irrespective of the timeout decision
