### ISSUE TITLE
[democracy] move proposal enaction to the start of assigning phase

### ISSUE THREAD

**Issue by brenzi** [encointer/pallets#393]
The current implementation enacts at the beginning of *registering* phase. This leads to inconsistent rewards if the proposal adjusts community issued income as some may claim early (during attesting) and others during registering (late claim). 

Options:
* at start of *registering*.
   * con: see above: potentially inconsistent CII
* at start of *assigning*.
   * pro: allows swift adding of new locations (only if onCeremonyPhaseChange is executed before ceremony pallet where assignment happens: must be well documented). In emergencies, a proposal could be submitted and approved during a single registering phase and enacted for the same cycle)
   * con: none
* at start of *attesting*.
   * con: possible inconsistency if assigning had different rules than meetup evaluation

**Comment by brenzi** [comment]
@pifragile any considerations to add?

**Comment by pifragile** [comment]
seems legit @brenzi
