### ISSUE TITLE
rust toolchain Improvements and fix clippy

### ISSUE THREAD

**Issue by clangenb** [encointer/pallets#59]
- [x] add rustfmt.toml: https://github.com/encointer/encointer-node/blob/master/rustfmt.toml
- [x] upgrade rust-toolchain to rust-toolchain.toml: https://github.com/integritee-network/parachain/blob/master/rust-toolchain.toml
- [ ] fix clippy warnings

**Comment by brenzi** [comment]
after recent refactorings, it may be a good time to tackle clippy now

**Comment by clangenb** [comment]
After fixing this, please enable the command in the CI, such that it fails if clippy is no longer happy: https://github.com/encointer/pallets/blob/588953ebf300e51e1d7a752be1a72997dc526cf9/.github/workflows/ci.yml#L30
