### ISSUE TITLE
rename CurrencyIdentifier to CommunityIdentifier

### ISSUE THREAD

**Issue by brenzi** [encointer/pallets#6]
...because it's not only about currency. Also root-of-trust for SSI

**Comment by clangenb** [comment]
How about renaming the entire `pallet-encointer-currencies` to `pallet-encointer-communities`?

This is motivated by a change to the currencies pallet necessary for #16, where I intend to add the mechanism of endorsing and managing newcomer tickets in the currencies module. @brenzi what do you think?

**Comment by brenzi** [comment]
yes, that would be the consequence

**Comment by clangenb** [comment]
This was closed with #19.
