### ISSUE TITLE
Enhance new assignment algorithm

### ISSUE THREAD

**Issue by NicJak** [encointer/pallets#75]
https://github.com/encointer/pallets/pull/68

At first glance, the code from the pull request looks clean, but not encapsulated enough (function length above 100 lines of code). In order to increase maintainability, changes on top making the code more descriptive - if feasible - should be implemented.

**Comment by brenzi** [comment]
@NicJak as agreed with @pifragile , I'd like you to refactor the code with a timebox of <8h such that we can merge and integrate the new flow into node and clients

**Comment by clangenb** [comment]
Closed with #68
