### ISSUE TITLE
council-permissioned community and ceremony management

### ISSUE THREAD

**Issue by brenzi** [encointer/pallets#77]
currently, everyone can register a new community and other permissioned functions are not really in line with the new common good governance through a council origin

https://github.com/paritytech/polkadot/blob/7a532985a3ccdf4f0c2fbc4b50e1e0806937391f/runtime/polkadot/src/lib.rs#L183-L187

An example how to use this generically in a pallet:
https://github.com/paritytech/substrate/blob/1b646b219e0e0c7489a2a8488381fc2e32da6a1c/frame/identity/src/lib.rs#L144
https://github.com/paritytech/substrate/blob/1b646b219e0e0c7489a2a8488381fc2e32da6a1c/frame/identity/src/lib.rs#L828

The following dispatchables should only be executed upon council motion, so we need to introduce a special origin that will be configured in the runtime instanciation

# communities
all of these should require council origin and be feeless

new_community, currently unpermissioned
https://github.com/encointer/pallets/blob/47282e2a5fe856884fcc875c89a8bdc8fc317435/communities/src/lib.rs#L82-L90

and bootstrappers can add/remove new locations:
https://github.com/encointer/pallets/blob/47282e2a5fe856884fcc875c89a8bdc8fc317435/communities/src/lib.rs#L139-L144

and it takes root origin to migrate metadata, demurrage, UBI:
https://github.com/encointer/pallets/blob/47282e2a5fe856884fcc875c89a8bdc8fc317435/communities/src/lib.rs#L203-L204

# scheduler
all of these should require council origin and be feeless

It currently takes a genesis-defined CeremonyMaster to:

modify ceremony schedule

https://github.com/encointer/pallets/blob/47282e2a5fe856884fcc875c89a8bdc8fc317435/scheduler/src/lib.rs#L80-L82

https://github.com/encointer/pallets/blob/47282e2a5fe856884fcc875c89a8bdc8fc317435/scheduler/src/lib.rs#L89-L91

**Comment by clangenb** [comment]
> and it takes root origin to migrate metadata, demurrage, UBI:
Why do we not want to allow bootstrappers changing the metadata? Will we just enable that later?
