### ISSUE TITLE
Allow to unregister from a ceremony?

### ISSUE THREAD

**Issue by clangenb** [encointer/pallets#78]
In the encointer-app we have the placeholder `Unregister` button in case somebody wants to unregister from the coming ceremony with the idea that this should be implemented.

I am not certain if this should be implemented because:

* If we don't implement an incentive to unregister, I reckon this will not be used even if a participant doesn't intend to show up. Hence, the incentive should probably be to punish no-shows, but this will be hard to fine-tune.

**Comment by brenzi** [comment]
a use case could be that Alice registers in Zurich but then plans a trip to Berlin so she'd like to change her registration from one community to another. we could just reject registering more than once. but, again, that would be easy to circumvent as we allow to use a fresh account for every ceremony anyway. So I do agree. makes no sense
