### ISSUE TITLE
[ceremonies] test remaining whitepaper rules

### ISSUE THREAD

**Issue by clangenb** [encointer/pallets#88]
We've had these todo's for ages in the test file. It is better to track that as an issue.

```
// TODO: whitepaper III-B Rule 1: minimize the number of participants that have met at previous ceremony
// TODO: whitepaper III-B Rule 2: maximize number of participants per meetup within 3<=N<=12
```

**Comment by brenzi** [comment]
these rules are not valid anymore with the new assignment algo. Not possible anymore to enfore heuristics with the new algo. We'll rather update the whitepaper. Please just remove the comments

**Comment by clangenb** [comment]
Ah, yes of course.

The comments are removed. Do you want to keep this issue open until the whitepaper has been updated?

**Comment by brenzi** [comment]
nah
