### ISSUE TITLE
[ceremonies] double check if we test well enough

### ISSUE THREAD

**Issue by clangenb** [encointer/pallets#89]
The code in the ceremonies is logically quite complex. I am afraid that we don't test enough, and don't test everything yet. I would like to do the following:

* [ ] double check that every piece of code is tested (code coverage)
* [ ] double-check that we have enough test-cases for the functions
* [ ] Don't neglect the randomness in the tests
* [ ] tests must provoke all defined `Error`s
* [ ] tests must cover all disposed `Event`s

**Comment by brenzi** [comment]
I think we also should make the grow-community unittest parametric and come up with various scenarios

**Comment by clangenb** [comment]
* We greatly extended the tests with https://github.com/encointer/pallets/pull/221
